CREATE DATABASE customer_behavior;

use customer_behavior

SELECT TOP 10 *
FROM dbo.customer;

---- 01. what is the total revenue generated by male vs female customers.?

select gender, sum(purchace_amount) as Total_revenue
from dbo.customer
group by gender

----Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchace_amount
from dbo.customer
where discount_applied = 'yes' and purchace_amount >=(select avg(purchace_amount) from dbo.customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased, round(avg(cast(review_rating as decimal(10,2))),2) as avg_review_rating
from dbo.customer
group by item_purchased
order by avg_review_rating desc


----Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 


select shipping_type, 
AVG(purchace_amount) as avg_purchase_amount
from dbo.customer
where shipping_type in ('Standard','Express')
group by shipping_type;


----Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select  subscription_status, count(customer_id) as total_customers, 
avg(purchace_amount) as avg_spend,
sum(purchace_amount) as total_Revenue
from dbo.customer
group by subscription_status
order by total_Revenue, avg_spend desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5
       item_purchased,
       ROUND(
           100.0 * SUM(
               CASE 
                   WHEN discount_applied = 'Yes' THEN 1 
                   ELSE 0 
               END
           ) / COUNT(*),
           2
       ) AS discount_rate
FROM dbo.customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as(
select customer_id, previous_purchases,
case
    when previous_purchases =1 then 'New'
    when previous_purchases Between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_Segment
from dbo.customer)

select customer_segment, count(*) as Number_of_customers
from customer_type
group by customer_Segment

--Q8. What are the top 3 most purchased products within each category? 

with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over( partition by category order by count(customer_id)desc) as item_rank
from dbo.customer
group by category, item_purchased)

select item_rank, category,item_purchased, total_orders
from item_counts
where item_rank <=3;



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from dbo.customer
where previous_purchases >5 
group by subscription_status 

--Q10. What is the revenue contribution of each age group? 

select  age_group,
sum(purchace_amount) as total_revenue
from dbo.customer
group by age_group
order by total_revenue desc
